version: '3.8'

networks:
  appoint:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: appoint-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-appoint}
      POSTGRES_USER: ${DB_USER:-appoint}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-appoint}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - appoint
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-appoint} -d ${DB_NAME:-appoint}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: appoint-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      - postgres
    networks:
      - appoint
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./db/pgadmin/servers.json:/pgadmin4/servers.json:ro

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: appoint-ui
    ports:
      - "${UI_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - appoint

volumes:
  postgres_data:
  pgadmin_data:
