# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and run tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Backend Tests

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'backend/yarn.lock'
      - name: Install backend dependencies
        run: yarn install
        working-directory: backend
      - name: Build backend
        run: yarn build
        working-directory: backend
      - name: Test backend
        run: yarn test
        working-directory: backend

  ui:
    runs-on: ubuntu-latest
    name: UI Tests

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'ui/yarn.lock'
      - name: Install UI dependencies
        run: yarn install
        working-directory: ui
      - name: Build UI
        run: yarn build
        working-directory: ui
      - name: Lint UI
        run: yarn lint
        working-directory: ui

